server:
  port: ${PORT}

spring:
  application:
    name: bookapi
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

javers:
  mongodb:
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
